function WriteCommand(Command, filename)
% WriteCommand writes a new command file.
%
%   WriteCommand(Command, filename) writes the structure Command to the command
%   file specified by filename.
%

fid = fopen(filename, 'w');

fn = fieldnames(Command);
filefields = {...
'Segment file name: %s\n',...
'Station file name: %s\n',...
'Block file name: %s\n',...
'SAR file name: %s\n',...
'Reuse old elastic kernel: %s\n',...
'Old elastic kernel file: %s\n',...
'Save current elastic kernels: %s\n',...
'Fault resolution: %g\n',...
'Poissons ratio: %g\n',...
'Station data weight: %g\n',...
'Station data weight minimum: %g\n',...
'Station data weight maximum: %g\n',...
'Station data weight steps: %g\n',...
'SAR data uncertainty: %g\n',...
'SAR data weight: %g\n',...
'Slip constraint weight: %g\n',...
'Slip constraint weight minimum: %g\n',...
'Slip constraint weight maximum: %g\n',...
'Slip constraint weight steps: %g\n',...
'Block constraint weight: %g\n',...
'Block constraint weight minimum: %g\n',...
'Block constraint weight maximum: %g\n',...
'Block constraint weight steps: %g\n',...
'Locking depth toggle 2: %g\n',...
'Locking depth toggle 3: %g\n',...
'Locking depth toggle 4: %g\n',...
'Locking depth toggle 5: %g\n',...
'locking depth override toggle: %s\n',...
'locking depth override value: %g\n',...
'Triangulated patch files: %s\n',...
'Creep rate distribution toggle: %g\n',...
'Creep rate constraint weight: %g\n',...
'Patch slip distribution files: %g\n',...
'Mesh smoothing values: %g\n',...
'Surface azimuth of triangular slips: %g\n',...
'Enforce patch kinematic consistency: %g\n',...
'Constrain edge element slip to equal that of adjacent segment: %g\n',...
'Set [up- down-] dip limits to zero slip: %g\n',...
'Strain calculation method: %g\n', ...
'Number of Monte Carlo iterations: %g\n'};

structfields = {...
'segFileName',...
'staFileName',...
'blockFileName',...
'sarFileName',...
'reuseElastic',...
'reuseElasticFile',...
'saveKernels',...
'faultRes',...
'poissonsRatio',...
'stationDataWgt',...
'stationDataWgtMin',...
'stationDataWgtMax',...
'stationDataWgtSteps',...
'sarSig',...
'sarWgt',...
'slipConWgt',...
'slipConWgtMin',...
'slipConWgtMax',...
'slipConWgtSteps',...
'blockConWgt',...
'blockConWgtMin',...
'blockConWgtMax',...
'blockConWgtSteps',...
'ldTog2',...
'ldTog3',...
'ldTog4',...
'ldTog5',...
'ldOvTog',...
'ldOvValue',...
'patchFileNames',...
'patchCreepTog',...
'creepConWgt',...
'slipFileNames',...
'triSmooth',...
'triRake',...
'triKinCons',...
'smoothEdge',...
'triEdge',...
'strainMethod',...
'nIter'}; 

% Match structure fields to file fields
[match, midx] = ismember(fn, structfields);

% A few patch-related things...
numpatch = length(strfind(Command.patchFileNames, ' ')) + 1;
filefields{34} = ['Mesh smoothing values: ' repmat('%g ', 1, numpatch) '\n'];
numz = min(numpatch, ceil(length(Command.triEdge)/3));
filefields{38} = ['Set [up- down- side] dip limits to zero slip: ' repmat('%g ', 1, 3*numz) '\n'];

midx = sort(nonzeros(midx));
% Write data to new command file
for i = 1:length(midx)
   fprintf(fid, filefields{midx(i)}, getfield(Command, structfields{midx(i, :)}(:)'));
end

fclose(fid);